### ISSUE TITLE
[Bug] Ignore Typescript references as DOM interfaces 

### ISSUE THREAD

**Issue by prabeengiri** [kopiro/eslint-plugin-ssr-friendly#17]
We just added eslint rule `ssr-friendly/no-dom-globals-in-react-fc` in our project. However, its complaining when using DOM interfaces as types in the hook. 

Eg. 
```
const rootRef = React.useRef<HTMLDivElement>(null)
```  
Lint Error: 
```
Use of DOM global 'HTMLDivElement' is forbidden in the render-cycle of a React FC, consider moving this inside useEffect()
```

Is there any way we can ignore if DOM interfaces are used as types in the hook?

**Comment by prabin-giri-dd** [comment]
Looks like we were using the older version of the plugin, the newer version seems to fix the Typescript issue.

**Comment by prabeengiri** [comment]
Looks like we were using the older version(1.0.5) of the plugin, the newer version (1.0.6) seems to fix the Typescript issue.
